apiVersion: v1
kind: Service
metadata:
  name: {{ include "costobs.fullname" . }}-ingest
  labels:
    {{- include "costobs.componentLabels" (dict "ctx" . "component" "ingest") | nindent 4 }}
spec:
  type: {{ .Values.ingest.service.type }}
  ports:
    - name: http
      port: {{ .Values.ingest.service.port }}
      targetPort: http
  selector:
    {{- include "costobs.componentSelectorLabels" (dict "ctx" . "component" "ingest") | nindent 4 }}
